### ISSUE TITLE
boss/gang menu not working

### ISSUE THREAD

**Issue by ggoodell2** [Qbox-project/qbx_management#28]
### Summary

option for boss menu comes up but boss menu itself does not open.

### Reproduction

any job gang script. option to open job menu comes up. press e and nothing happens.

### Expected behavior

job menu to open

### Actual behavior

nothing

### Last Updated

today

### Custom Resources

wasabi ambulance and police

### Resource Rename

none

**Comment by mafewtm** [comment]
Did you add the export to the server.lua properly?
