### ISSUE TITLE
Add type = 'job' reference to qbx-management

### ISSUE THREAD

**Issue by bluelineparabellum** [Qbox-project/qbx_management#54]
### The problem

I didn't realize this was needed, thought there was only gangs or I could make my own. So this would be great for newer people.

### Ideal solution

Add type = 'job' reference in file.

**Comment by mafewtm** [comment]
I'm confused on what the issue is?

**Comment by solareon** [comment]
I believe they mean the examples in the boss menu config only show gangs so they weren't aware you could put job in there.

**Comment by mafewtm** [comment]
I didn't think I really had to annotate gang and job when it says GroupType.
It's also right here too https://docs.qbox.re/resources/qbx_management/exports/server#registerbossmenu
