### ISSUE TITLE
qbx management broken when trying to access player list

### ISSUE THREAD

**Issue by alberttheprince** [Qbox-project/qbx_management#56]
### Summary

Breaks when trying to view employees

### Reproduction

1. Open Menu
2. Try to access list of employees
3. Qbx_management breaks

### Expected behavior

1. Open Menu
2. Try to access list of employees
3. View list, hire/fire/manage

### Actual behavior

Menu breaks when trying to access list of employees

### Additional context

Server side errors:
![image](https://github.com/Qbox-project/qbx_management/assets/85725579/de7afb2f-29b0-4267-ac33-a425cbbdba7b)

Client side errors:
![image](https://github.com/Qbox-project/qbx_management/assets/85725579/e4e9abed-074a-4409-9c64-d75665c1ecbb)

### Current Version

1.10.1

### Custom Resources

N/A

**Comment by Pilpest** [comment]
https://github.com/Qbox-project/qbx_core/blob/98ce3316fed733afdb2ed3e81f026eb92d711239/server/player.lua#L315

Related to this, it's trying to grab it for offline players as well which is invalid. Would be best to put it in the;

`if source then` section just below it.

**Comment by Alexxxunchained** [comment]
I just set up a brand new qbx server and this problems happends again

**Comment by Alexxxunchained** [comment]
@Manason Sorry for ask, but its the way to fix this? → "fix(server/player): more offline player checks". Do I have to make the code change just like this post?

**Comment by Manason** [comment]
You can see if that fixes it, or wait for that code change to make it into the next release.

**Comment by Alexxxunchained** [comment]
Okay mate, I've tired this change but still same error, lets waitting for management update

**Comment by Manason** [comment]
@Alexxxunchained What version of qbx_core and qbx_management are you on?

**Comment by Alexxxunchained** [comment]
qbx_core: 1.17.2, qbx_management: '1.2.0'

**Comment by Manason** [comment]
Try qbx_core v1.18.1 and qbx_management v1.3.0

**Comment by Alexxxunchained** [comment]
Sorry mate, but where can I find qbx_management v1.3.0?

**Comment by Manason** [comment]
My bad. qbx_management v1.2.0 is the latest one. Does this error still show up on qbx_core v1.18.1?

**Comment by Alexxxunchained** [comment]
This problem is solved for now, the reason caused this error is when u using the old server's database sql file (at least in my side), the way to fix it is to do:
1. In your heidiSQL
2. Find the table: player_groups, then wipe everything in it
3. Find the row: job and gang in players table, then set job content to unemployed and set gang to No gang
4. All good to go
