### ISSUE TITLE
[Request] Backwards compatability

### ISSUE THREAD

**Issue by MrNewb** [Qbox-project/qbx_management#57]
### The problem

Currently this does not handle plug n play backwards compatibility, this request is to provide the normal events to keep qbx as an easy transition.

### Ideal solution

handle qb-bossmenu/qb-managment events for registering the menus. (this will make qbx adoption significantly more likely for many) 

### Alternative solutions

Not and just expecting people to add their own compatibility. 

### Additional context

I manually adjust myself, but I do not feel a pr for my way of doing this with the events comes even remotely close to qbxs style of doing this. Just an idea, because these old events are widely used (even by some qbx partners like wasabi)

**Comment by Manason** [comment]
Doesn't qb-management work if someone wants backwards compat?

**Comment by solareon** [comment]
> Doesn't qb-management work if someone wants backwards compat?

Yes but then they lose the ability to manage the built in multi job/gang.

@MrNewb could you share an example of what event is being triggered in qb-management?

**Comment by MrNewb** [comment]
I mean the event handlers to convert to the new functions.
What would be nice is have something to provide for events like ```qb-bossmenu:client:OpenMenu``` and the qb-managment alternatives commonly used


Best example I can provide is just how often that event is used

https://github.com/search?q=qb-bossmenu%3Aclient%3AOpenMenu&type=code

Some creators in a majority of servers still using these events
wasabi
rcore
and many more


This event I think was in qb-managment for its previous version was a compatibility thing but is used most commonly


https://github.com/wasabirobby/resources/blob/04424fedae63aaa13f55aa189fe114f9d6bf809d/%5Bqb%5D/%5Bauxiliary%5D/wasabi_police/bridge/qb/client.lua#L107

**Comment by EdFiveM** [comment]
so will this feature be added? for compatibility with qb-management?

**Comment by Manason** [comment]
If someone wants to PR it, I'm not against it, but I don't think it's needed. People can use qb-management which is compatible with qbx_core. multijob/multigang isn't compatible with qb-management either way.

**Comment by mafewtm** [comment]
Implemented as of 3a336e1 and a8c3ba0
