### ISSUE TITLE
Server error when boss hires/fires from boss menu

### ISSUE THREAD

**Issue by bluelineparabellum** [Qbox-project/qbx_management#70]
### Summary

Server Error - Boss Menu

### Reproduction

1. Boss accesses boss menu
2. Boss hires or fires player. When boss promotes or demotes, it also happens. Seems to be working and going through for SQL but error showing in server console.

### Expected behavior

Expected no server errors

### Actual behavior

Server errors.

### Additional context

```lua
[script:qbx_managemen] SCRIPT ERROR: @qbx_management/server/main.lua:176: attempt to index a nil value (local 'errorResult')
[script:qbx_managemen] > callbackResponse (@ox_lib/imports/callback/server.lua:79)
[script:qbx_managemen] > handler (@ox_lib/imports/callback/server.lua:96)
[script:qbx_managemen] > rawQuery (@oxmysql/dist/build.js:27077)
[script:qbx_managemen] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:qbx_managemen] 
[script:qbx_managemen] SCRIPT ERROR: @qbx_management/server/main.lua:107: attempt to index a nil value (local 'errorResult')
[script:qbx_managemen] 
[script:qbx_managemen] SCRIPT ERROR: @qbx_management/server/main.lua:75: attempt to index a nil value (local 'errorResult')
[script:qbx_managemen] 
```

### Current Version

v1.2.1

### Custom Resources

N/A

**Comment by RealisticLifeRP** [comment]
![image](https://github.com/user-attachments/assets/135e9047-8dcc-4619-84f3-7de488625ecb)

Having same issue as well

**Comment by D4isDAVID** [comment]
Hi, please try with PR #77.

**Comment by bluelineparabellum** [comment]
> Hi, please try with PR #77.

Ill try it out. Thanks!
**EDIT:** Looks great. Love the additions to employees section!
